# Generated by Django 4.2 on 2023-04-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("project", models.JSONField()),
                ("wall", models.CharField(max_length=128)),
                ("roof", models.CharField(max_length=128)),
                ("floor", models.CharField(max_length=128)),
            ],
        ),
    ]
