# Generated by Django 4.2 on 2023-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ulca", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="uvalue",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
