# Generated by Django 4.2 on 2023-04-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ulca", "0002_building_uvalue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="uvalue",
            new_name="floorUvalue",
        ),
        migrations.AddField(
            model_name="building",
            name="roofUvalue",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="building",
            name="wallUvalue",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
